import{a as b,S as L,i as u}from"./assets/vendor-DtOuICiv.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const v="49376461-7308a4eb46f734d3329281beb";async function h(t,r=1,n=40){try{return(await b.get("https://pixabay.com/api/",{params:{key:v,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:n}})).data}catch(i){return console.error("Error loading images:",i),{hits:[]}}}const y=document.querySelector(".gallery"),q=new L(".gallery a",{captionsData:"alt",captionDelay:250});function P(t){return t.map(({webformatURL:r,largeImageURL:n,tags:i,likes:e,views:o,comments:s,downloads:g})=>`
        <li class="gallery-item">
          <a href="${n}">
            <img src="${r}" alt="${i}" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${e}</p>
            <p><b>Views:</b> ${o}</p>
            <p><b>Comments:</b> ${s}</p>
            <p><b>Downloads:</b> ${g}</p>
          </div>
        </li>`).join("")}function p(t){y.innerHTML=P(t),q.refresh()}function S(){y.innerHTML=""}const w=document.querySelector(".form"),$=document.querySelector('input[name = "search-text"]'),l=document.querySelector(".loader"),m=document.querySelector(".btnLoad-more"),f=15;let d=0,a=1,c="";w.addEventListener("submit",E);m.addEventListener("click",O);async function E(t){if(t.preventDefault(),c=$.value.trim(),!c){u.info({title:"Hello",message:"Please enter your query"});return}a=1,l.classList.remove("hidden"),S();try{const r=await h(c,a,f);if(r.hits.length===0){u.info({title:"Sorry",message:"There are no images matching your search query. Please try again!"});return}d=Math.ceil(r.totalHits/f),p(r.hits),m.classList.toggle("hidden",a>=d)}catch(r){console.error("Failed to fetch images. Try again later!",r)}finally{l.classList.add("hidden")}}async function O(){if(!(a>=d)){a+=1,l.classList.remove("hidden");try{const t=await h(c,a,f);p(t.hits),x(),a>=d&&(m.classList.add("hidden"),u.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."}))}catch(t){console.error("Failed to fetch more images:",t)}finally{l.classList.add("hidden")}}}function x(){const t=document.querySelector(".gallery-item");if(t){const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
