import{a as b,S as L,i as f}from"./assets/vendor-DtOuICiv.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const v="49376461-7308a4eb46f734d3329281beb";async function h(t,r=1,a=40){try{return(await b.get("https://pixabay.com/api/",{params:{key:v,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:a}})).data}catch(i){return console.error("Error loading images:",i),{hits:[]}}}const y=document.querySelector(".gallery"),q=new L(".gallery a",{captionsData:"alt",captionDelay:250});function P(t){return t.map(({webformatURL:r,largeImageURL:a,tags:i,likes:e,views:o,comments:n,downloads:g})=>`
        <li class="gallery-item">
          <a href="${a}">
            <img src="${r}" alt="${i}" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${e}</p>
            <p><b>Views:</b> ${o}</p>
            <p><b>Comments:</b> ${n}</p>
            <p><b>Downloads:</b> ${g}</p>
          </div>
        </li>`).join("")}function p(t){y.insertAdjacentHTML("beforeend",P(t)),q.refresh()}function S(){y.innerHTML=""}const w=document.querySelector(".form"),$=document.querySelector('input[name = "search-text"]'),c=document.querySelector(".loader"),d=document.querySelector(".btnLoad-more"),m=15;let u=0,s=1,l="";w.addEventListener("submit",E);d.addEventListener("click",O);async function E(t){if(t.preventDefault(),l=$.value.trim(),!l){f.info({title:"Hello",message:"Please enter your query"});return}s=1,c.classList.remove("hidden"),S(),d.classList.add("hidden");try{const r=await h(l,s,m);if(r.hits.length===0){f.info({title:"Sorry",message:"There are no images matching your search query. Please try again!"}),c.classList.add("hidden");return}u=Math.ceil(r.totalHits/m),p(r.hits),s<u&&d.classList.remove("hidden")}catch(r){console.error("Failed to fetch images. Try again later!",r)}finally{c.classList.add("hidden")}}async function O(){if(!(s>=u)){s+=1,c.classList.remove("hidden");try{const t=await h(l,s,m);p(t.hits),x(),s>=u&&(d.classList.add("hidden"),f.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."}))}catch(t){console.error("Failed to fetch more images:",t)}finally{c.classList.add("hidden")}}}function x(){const t=document.querySelectorAll(".gallery-item");if(t.length>0){const r=t[0].getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
